# Generated by Django 6.0 on 2025-12-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0002_alter_city_source_province_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postalinfo_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
