# Generated by Django 6.0 on 2025-12-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='source_province_id',
            field=models.BigIntegerField(blank=True, help_text='ID of province from source repository', null=True),
        ),
    ]
